version: '3.3'
services:
  java-srv:
    build:
      context: java-srv
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && gradle run"
    env_file:
      - ./db.env
    environment:
      - WAIT_HOSTS=db:5000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=60
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ./java-srv/log:/root/log

  db:
    image: datagrip/sybase
    ports:
      - 5000:5000
    environment:
      - SYBASE_USER:sa
      - SYBASE_PASSWORD:myPassword
